// <auto-generated />
using System;
using LIMS.Service.Methodologies.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIMS.Service.Methodologies.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818124344_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.Entities.CalculationRules.CalculationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormulaExpression")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ResultDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.ToTable("CalculationRules", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.Entities.InputParameters.InputParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId", "AliasName")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("InputParameters", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.Entities.ResultDefinitions.ResultDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResultInstance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("StudyTemplateId", "ResultInstance", "UnitId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("ResultDefinitions", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Revision")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StudyTemplates", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.UnitSnapshots.UnitSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("UnitSnapshots", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.Entities.CalculationRules.CalculationRule", b =>
                {
                    b.HasOne("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("CalculationRules")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.Entities.InputParameters.InputParameter", b =>
                {
                    b.HasOne("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("InputParameters")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.Service.Methodologies.Domain.SeedWork.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("InputParameterId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMaxValue");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMinValue");

                            b1.HasKey("InputParameterId");

                            b1.ToTable("InputParameters");

                            b1.WithOwner()
                                .HasForeignKey("InputParameterId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.Entities.ResultDefinitions.ResultDefinition", b =>
                {
                    b.HasOne("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("ResultDefinitions")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIMS.Service.Methodologies.Domain.UnitSnapshots.UnitSnapshot", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LIMS.Service.Methodologies.Domain.SeedWork.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("ResultDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMaxValue");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMinValue");

                            b1.HasKey("ResultDefinitionId");

                            b1.ToTable("ResultDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ResultDefinitionId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.Methodologies.Domain.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Navigation("CalculationRules");

                    b.Navigation("InputParameters");

                    b.Navigation("ResultDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
