// <auto-generated />
using System;
using LIMS.Service.LaboratoryOperations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIMS.Service.LaboratoryOperations.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contractor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.SampleAggregate.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SampleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("OrderId");

                    b.ToTable("Samples", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Entities.MeasuredValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InputParameterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("InputParameterId");

                    b.HasIndex("StudyId");

                    b.ToTable("MeasuredValues", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOutOfSpec")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResultDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ResultDefinitionId");

                    b.HasIndex("StudyId");

                    b.ToTable("TestResults", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("StudyTemplateId");

                    b.ToTable("Studies", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.CalculationRules.CalculationRuleSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormulaExpression")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ResultDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.ToTable("CalculationRuleCalculationRuleSnapshots", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.InputParameters.InputParameterSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.ToTable("InputParameterSnapshots", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.ResultDefinitions.ResultDefinitionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResultInstance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.HasIndex("UnitId");

                    b.ToTable("ResultDefinitionSnapshots", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.StudyTemplateSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Revision")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StudyTemplateSnapshots", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.UnitSnapshots.UnitSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("UnitSnapshots", (string)null);
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.SampleAggregate.Sample", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.OrderAggregate.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LIMS.Service.LaboratoryOperations.Domain.SampleAggregate.ValueObjects.GatherDate", "GatherDate", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("Begin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("GatherDateBegin");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("GatherDateEnd");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");
                        });

                    b.OwnsOne("LIMS.Service.LaboratoryOperations.Domain.SampleAggregate.ValueObjects.Volume", "Volume", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("UnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("VolumeUnitId");

                            b1.Property<double?>("Value")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("VolumeValue");

                            b1.HasKey("SampleId");

                            b1.HasIndex("UnitId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");

                            b1.HasOne("LIMS.Service.LaboratoryOperations.Domain.UnitSnapshots.UnitSnapshot", null)
                                .WithMany()
                                .HasForeignKey("UnitId")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.Navigation("GatherDate")
                        .IsRequired();

                    b.Navigation("Volume")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Entities.MeasuredValue", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.InputParameters.InputParameterSnapshot", null)
                        .WithMany()
                        .HasForeignKey("InputParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Study", null)
                        .WithMany("MeasuredValues")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Entities.TestResult", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.ResultDefinitions.ResultDefinitionSnapshot", null)
                        .WithMany()
                        .HasForeignKey("ResultDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Study", null)
                        .WithMany("TestResults")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Study", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.SampleAggregate.Sample", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.StudyTemplateSnapshot", null)
                        .WithMany()
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.CalculationRules.CalculationRuleSnapshot", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.StudyTemplateSnapshot", null)
                        .WithMany("CalculationRules")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.InputParameters.InputParameterSnapshot", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.StudyTemplateSnapshot", null)
                        .WithMany("Parameters")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.SeedWork.SeedWork.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("InputParameterSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("MaxValue");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("MinValue");

                            b1.HasKey("InputParameterSnapshotId");

                            b1.ToTable("InputParameterSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("InputParameterSnapshotId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.ResultDefinitions.ResultDefinitionSnapshot", b =>
                {
                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.StudyTemplateSnapshot", null)
                        .WithMany("Results")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIMS.Service.LaboratoryOperations.Domain.UnitSnapshots.UnitSnapshot", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.SeedWork.SeedWork.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("ResultDefinitionSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("MaxValue");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("MinValue");

                            b1.HasKey("ResultDefinitionSnapshotId");

                            b1.ToTable("ResultDefinitionSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("ResultDefinitionSnapshotId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyAggregate.Study", b =>
                {
                    b.Navigation("MeasuredValues");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("LIMS.Service.LaboratoryOperations.Domain.StudyTemplateSnapshots.StudyTemplateSnapshot", b =>
                {
                    b.Navigation("CalculationRules");

                    b.Navigation("Parameters");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
