<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5"><PrivateAssets>all</PrivateAssets></PackageReference>
    <ProjectReference Include="../../src/Service.Guides.Application/Service.Guides.Application.csproj" />
    <ProjectReference Include="../../src/Service.Guides.API/Service.Guides.API.csproj" />
    <ProjectReference Include="../../src/Service.Guides.Persistence/Service.Guides.Persistence.csproj" />
  </ItemGroup>
</Project>