<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="StudyTemplateAggregate\ValueObjects\Description.cs">
      <Generator>MSBuild:GenerateCodeFromAttributes</Generator>
    </Compile>
    <Compile Update="StudyTemplateAggregate\ValueObjects\Name.cs">
      <Generator>MSBuild:GenerateCodeFromAttributes</Generator>
    </Compile>
    <Compile Update="SeedWork\ValueObjects\Description.cs">
      <Generator>MSBuild:GenerateCodeFromAttributes</Generator>
    </Compile>
    <Compile Update="SeedWork\ValueObjects\Name.cs">
      <Generator>MSBuild:GenerateCodeFromAttributes</Generator>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="StudyTemplateContext\" />
    <Folder Include="StudyTemplateContext\StudyTemplateAggregate\ValueObjects\StatusState\" />
  </ItemGroup>

</Project>
