<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    <PackageReference Include="StronglyTypedId" Version="0.2.1"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Description.cs">
      <Generator>MSBuild:GenerateCodeFromAttributes</Generator>
    </Compile>
    <Compile Update="Name.cs">
      <Generator>MSBuild:GenerateCodeFromAttributes</Generator>
    </Compile>
  </ItemGroup>

</Project>
