<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LIMS.Service.Methodologies.Domain\LIMS.Service.Methodologies.Domain.csproj"/>
    <ProjectReference Include="..\RabbitMq.Library.Outbox.Abstractions\RabbitMq.Library.Outbox.Abstractions.csproj"/>
    <ProjectReference Include="..\RabbitMq.Library.Outbox\RabbitMq.Library.Outbox.csproj"/>
  </ItemGroup>

</Project>
