// <auto-generated />
using System;
using LIMS.DDD.Service.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIMS.DDD.Service.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806123511_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contractor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.SampleAggregate.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SampleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("OrderId");

                    b.ToTable("Samples", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Entities.MeasuredValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("MeasuredValues", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOutOfSpec")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("TestResults", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("Name", "SampleId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Studies", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.CalculationRules.CalculationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormulaExpression")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ResultDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.ToTable("CalculationRules", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.InputParameters.InputParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId", "AliasName")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("InputParameters", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.ResultDefinitions.ResultDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResultInstance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId", "ResultInstance", "Unit")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("ResultDefinitions", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Revision")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("StudyTemplates", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.SampleAggregate.Sample", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.OrderAggregate.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.SampleAggregate.ValueObjects.GatherDate", "GatherDate", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("Begin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("GatherDateBegin");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("GatherDateEnd");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");
                        });

                    b.OwnsOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.SampleAggregate.ValueObjects.Volume", "Volume", b1 =>
                        {
                            b1.Property<Guid>("SampleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("VolumeUnit");

                            b1.Property<double?>("Value")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("VolumeValue");

                            b1.HasKey("SampleId");

                            b1.ToTable("Samples");

                            b1.WithOwner()
                                .HasForeignKey("SampleId");
                        });

                    b.Navigation("GatherDate")
                        .IsRequired();

                    b.Navigation("Volume")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Entities.MeasuredValue", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Study", null)
                        .WithMany("MeasuredValues")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.ValueObjects.ParameterSnapshot", "ParameterSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MeasuredValueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AliasName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ParamAliasName");

                            b1.Property<Guid>("InputParameterId")
                                .HasColumnType("uuid")
                                .HasColumnName("ParameterId");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ParamSpecMax");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ParamSpecMin");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ParamName");

                            b1.HasKey("MeasuredValueId");

                            b1.ToTable("MeasuredValues");

                            b1.WithOwner()
                                .HasForeignKey("MeasuredValueId");
                        });

                    b.Navigation("ParameterSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Entities.TestResult", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Study", null)
                        .WithMany("TestResults")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.ValueObjects.ResultSnapshot", "ResultSnapshot", b1 =>
                        {
                            b1.Property<Guid>("TestResultId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ResSpecMax");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ResSpecMin");

                            b1.Property<Guid>("ResultDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("ResultDefinitionId");

                            b1.Property<string>("ResultInstance")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ResInstance");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ResUnit");

                            b1.HasKey("TestResultId");

                            b1.ToTable("TestResults");

                            b1.WithOwner()
                                .HasForeignKey("TestResultId");
                        });

                    b.Navigation("ResultSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Study", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.SampleAggregate.Sample", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.CalculationRules.CalculationRule", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("CalculationRules")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.CalculationRules.ValueObjects.CalculationInput", "CalculationInputs", b1 =>
                        {
                            b1.Property<Guid>("CalculationRuleId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("ParameterId");

                            b1.Property<string>("VariableAlias")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.HasKey("CalculationRuleId", "__synthesizedOrdinal");

                            b1.ToTable("CalculationRules");

                            b1
                                .ToJson("CalculationInputs")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CalculationRuleId");
                        });

                    b.Navigation("CalculationInputs");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.InputParameters.InputParameter", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("InputParameters")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.SeedWork.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("InputParameterId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMaxValue");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMinValue");

                            b1.HasKey("InputParameterId");

                            b1.ToTable("InputParameters");

                            b1.WithOwner()
                                .HasForeignKey("InputParameterId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.ResultDefinitions.ResultDefinition", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("ResultDefinitions")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.SeedWork.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("ResultDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMaxValue");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision")
                                .HasColumnName("SpecMinValue");

                            b1.HasKey("ResultDefinitionId");

                            b1.ToTable("ResultDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ResultDefinitionId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.LaboratoryOperationsContext.StudyAggregate.Study", b =>
                {
                    b.Navigation("MeasuredValues");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Navigation("CalculationRules");

                    b.Navigation("InputParameters");

                    b.Navigation("ResultDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
