// <auto-generated />
using System;
using LIMS.DDD.Service.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIMS.DDD.Service.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Revision")
                        .IsUnique();

                    b.ToTable("StudyTemplates");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplateDeterminations.StudyTemplateDetermination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultInstance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.HasIndex("Unit", "ResultInstance")
                        .IsUnique();

                    b.ToTable("StudyTemplateDetermination");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplateObservations.StudyTemplateObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId");

                    b.ToTable("StudyTemplateObservations");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplateDeterminations.StudyTemplateDetermination", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("Determinations")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.StudyTemplateAggregate.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("StudyTemplateDeterminationId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision");

                            b1.HasKey("StudyTemplateDeterminationId");

                            b1.ToTable("StudyTemplateDetermination");

                            b1.WithOwner()
                                .HasForeignKey("StudyTemplateDeterminationId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplateObservations.StudyTemplateObservation", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("Observations")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.StudyTemplateAggregate.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("StudyTemplateObservationId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision");

                            b1.HasKey("StudyTemplateObservationId");

                            b1.ToTable("StudyTemplateObservations");

                            b1.WithOwner()
                                .HasForeignKey("StudyTemplateObservationId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Navigation("Determinations");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
