// <auto-generated />
using System;
using LIMS.DDD.Service.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIMS.DDD.Service.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.CalculationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormulaExpression")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ResultDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId", "Name")
                        .IsUnique();

                    b.ToTable("CalculationRules", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.InputParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId", "AliasName")
                        .IsUnique();

                    b.ToTable("InputParameters", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.ResultDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultInstance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudyTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudyTemplateId", "Unit", "ResultInstance")
                        .IsUnique();

                    b.ToTable("ResultDefinitions", (string)null);
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Revision")
                        .IsUnique();

                    b.ToTable("StudyTemplates");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.CalculationRule", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("CalculationRules")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.ValueObjects.CalculationInput", "CalculationInputs", b1 =>
                        {
                            b1.Property<Guid>("CalculationRuleId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("ParameterId");

                            b1.Property<string>("VariableAlias")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.HasKey("CalculationRuleId", "__synthesizedOrdinal");

                            b1.ToTable("CalculationRules");

                            b1
                                .ToJson("CalculationInputs")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CalculationRuleId");
                        });

                    b.Navigation("CalculationInputs");
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.InputParameter", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("InputParameters")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("InputParameterId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision");

                            b1.HasKey("InputParameterId");

                            b1.ToTable("InputParameters");

                            b1.WithOwner()
                                .HasForeignKey("InputParameterId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.Entities.ResultDefinition", b =>
                {
                    b.HasOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", null)
                        .WithMany("ResultDefinitions")
                        .HasForeignKey("StudyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.ValueObjects.Specification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("ResultDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxValue")
                                .HasColumnType("double precision");

                            b1.Property<double?>("MinValue")
                                .HasColumnType("double precision");

                            b1.HasKey("ResultDefinitionId");

                            b1.ToTable("ResultDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ResultDefinitionId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("LIMS.DDD.Service.Domain.StudyTemplateContext.StudyTemplateAggregate.StudyTemplate", b =>
                {
                    b.Navigation("CalculationRules");

                    b.Navigation("InputParameters");

                    b.Navigation("ResultDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
